;Missile Structure
MISSILE		equ	16
X_COORD		equ	0
Y_COORD		equ	2
SPEED		equ	4
VISIBLE		equ	5
BEHAV		equ	6
H_MOVE		equ	8
V_MOVE		equ	10
SPRITE		equ	12


;Missile behaviours
UP		equ	0
DOWN		equ	1
LEFT		equ	2
RIGHT		equ	3
EXPLODE		equ	4



;MISSILE_BEHAVIOUR(Missile* missile,H_DIRECTION h_direction, V_DIRECTION v_direction, MISSILE_BEHAVIOUR behaviour)
V_MISS		equ	8
H_DIR		equ	12
V_DIR		equ	14
M_BEHAV		equ	16








