all: clean model.tos

model.tos: bitmaps.o gameE.o model.o Assess.o Fonts.o BackDrop.o Grass.o GameF.o behavior.o missile.o AsRou.o renderE.o system.o keyboard.o 
	cc68x -g -v bitmaps.o gameE.o model.o Assess.o Fonts.o BackDrop.o Grass.o GameF.o behavior.o missile.o AsRou.o renderE.o system.o keyboard.o -o model.tos

model.o: model.c model.h behavior.h missile.h system.h keyboard.h Assess.h
	cc68x -g -c -v model.c model.h behavior.h missile.h system.h keyboard.h

behavior.o: behavior.c behavior.h
	cc68x -g -c -v behavior.c behavior.h model.h

missile.o: missile.c missile.h
	cc68x -g -c -v missile.c missile.h
	
bitmaps.o: bitmaps.c bitmaps.h
	cc68x -g -c -v bitmaps.c bitmaps.h
	
system.o: system.c system.h
	cc68x -g -c -v system.c system.h
	
keyboard.o: keyboard.c keyboard.h
	cc68x -g -c -v keyboard.c keyboard.h

gameE.o: gameE.c model.h renderE.h AsRou.h bitmaps.h behavior.h system.h keyboard.h
	cc68x -g -c -v gameE.c model.h BackDrop.h Grass.h GameF.h renderE.h AsRou.h bitmaps.h behavior.h system.h keyboard.h

renderE.o: renderE.c renderE.h
	cc68x -g -c -v renderE.c renderE.h

AsRou.o: AsRou.s
	gen -D -L2 AsRou.s
	
Assess.o: Assess.s Assess.h
	gen -D -L2 Assess.s
	
BackDrop.o: BackDrop.c BackDrop.h types.h RenderE.h
	cc68x -g -c -v BackDrop.c BackDrop.h types.h RenderE.h
	
Grass.o: Grass.c Grass.h
	cc68x -g -c -v Grass.c Grass.h
	
GameF.o: GameF.c GameF.h
	cc68x -g -c -v GameF.c GameF.h

Fonts.o: Fonts.c Fonts.h
	cc68x -g -c -v Fonts.c Fonts.h

clean: 
	$(RM) *.o *.i
