all: clean model.tos

model.tos: model.o behavior.o missile.o
	cc68x -g -v model.o behavior.o missile.o -o model.tos

model.o: model.c model.h
	cc68x -g -c -v model.c model.h

behavior.o: behavior.c behavior.h
	cc68x -g -c -v behavior.c behavior.h model.h

missile.o: missile.c missile.h
	cc68x -g -c -v missile.c missile.h
	
	
clean: 
	$(RM) *.o *.i
